language: go

go:
  - 1.10.x

script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/redis-health-linux-amd64
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o build/redis-health-darwin-amd64
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o build/redis-health-windows-amd64

deploy:
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file:
      - build/redis-health-linux-amd64
      - build/redis-health-darwin-amd64
      - build/redis-health-windows-amd64
    skip_cleanup: true
    overwrite: true
    on:
      repo: seatgeek/redis-health
      tags: true
